version: '2'

services:
  jenkins:
    image: jenkins-server
    container_name: 'jenkins'
    ports:
      - '80:8080'
    environment:
      - JENKINS_PASSWORD=bitnami
    volumes:
      - 'jenkins_data:/bitnami/jenkins'
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app_net

volumes:
  jenkins_data:
    driver: local
networks:
  app_net:
    external:
      name: app_net
